title: Rachel Chan # your name (or website title) here
logo: "images/profile picture.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, I'm Rachel, a Software Engineer based in London.
  <br><br>
  Upon graduating from UCL in 2019 having majored in Psychology and Language Sciences, I started my career in the tech industry as a Growth Hacker for a startup. I became intrigued in software development and joined QA Academy, learning a diverse set of languages and technologies detailed in my resume.
  <br><br>
  In my spare time, I love cooking and running my food blog [@itsrachelchan](https://www.instagram.com/itsrachelchan/).
  <br><br>
  <a href="https://www.linkedin.com/in/rachelhchan/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
